# Generated by Django 4.2.4 on 2023-08-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menu'),
        ),
        migrations.AlterField(
            model_name='liker',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resturant', to='account.resturants'),
        ),
    ]
