# Generated by Django 4.2.4 on 2023-08-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_like_menu_alter_liker_resturant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturants',
            name='save_manu',
        ),
        migrations.AddField(
            model_name='resturants',
            name='save_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='account.menu'),
        ),
    ]
