# Generated by Django 4.2.4 on 2023-08-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_resturants_save_manu_resturants_save_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturants',
            name='save_menu',
        ),
        migrations.AddField(
            model_name='user',
            name='resturant_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.resturants'),
        ),
        migrations.AddField(
            model_name='user',
            name='save_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.menu'),
        ),
    ]
