# Generated by Django 4.2.4 on 2023-08-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_resturants_save_menu_user_resturant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturants',
            name='save_manu',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
