# Generated by Django 4.2.4 on 2023-08-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_resturants_save_manu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturants',
            old_name='save_manu',
            new_name='save_menu',
        ),
    ]
