# Generated by Django 4.2.4 on 2023-08-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_save_manu_resturants_save_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='save_menu',
        ),
    ]
