# Generated by Django 4.2.4 on 2023-08-25 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_save_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resturant_name',
        ),
        migrations.AddField(
            model_name='user',
            name='save_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.resturants'),
        ),
    ]
