# Generated by Django 4.2.4 on 2023-08-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_menu_save_manu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturants',
            name='resturant_name',
            field=models.CharField(max_length=200),
        ),
    ]
