# Generated by Django 4.2.4 on 2023-08-25 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_save_manu_menu_save_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resturant_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='save_menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='save_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
