# Generated by Django 4.2.4 on 2023-08-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_save_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='save_menu',
        ),
        migrations.CreateModel(
            name='SaveMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.ManyToManyField(to='account.menu')),
                ('resturant_name', models.ManyToManyField(to='account.resturants')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
